version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 5  # Número de réplicas
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/my_conf.conf:/etc/nginx/conf.d/default.conf  # Mapeia a configuração do NGINX
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
