version: '3.8'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 5  # Número de réplicas
      placement:
        constraints: [node.role == worker]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/my_conf.conf:/etc/nginx/conf.d/default.conf  # Mapeia a configuração do NGINX
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - app-network

  visualizer:
      image: dockersamples/visualizer
      ports:
        - "8888:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      deploy:
        placement:
          constraints: [node.role==manager]
      networks:
        - app-network


networks:
  app-network:
    driver: overlay